version: '3.8'

services:
  database:
    image: 'postgres:15'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - bicycle-shop-database:/var/lib/postgresql/data

volumes:
  bicycle-shop-database:
    external: true
